volumes:
  vastgoedfiles:

services:
  funda-scraper:
    # image: idgis/funda-scraper:1.4.7
    build: .
    restart: always
    ports:
      - "8080:80"
    environment:
      GEMEENTE: gemeente-berkelland
      BEDRIJVENTERREINEN_FEATURES: https://bedrijventerreinen.gelderland.nl/geoserver/IBIS_Publiek/wfs?SERVICE=WFS&version=1.1.0&request=GetFeature&typeName=v_publieke_terreinen&outputFormat=application/json&bbox=220754,445975,251434,467576
    volumes:
      - vastgoedfiles:/home/meteorapp/build/bundle/programs/web.browser/app/data
